### ISSUE TITLE
Build fails on Ubuntu [Cereal Error]

### ISSUE THREAD

**Issue by shaheenkdr** [facebookresearch/flashlight#13]
I am trying to setup `flashlight` on an Ubuntu machine. Have installed all the dependencies: 

When I invoke : `cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CUDA`

I get the output as : 

```
-- ArrayFire found (include: /home/arrayfire/include, library: ArrayFire::afcuda)
-- cereal found (include: /usr/bin)
-- cereal found
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- Found CUDNN: (lib: /usr/lib/x86_64-linux-gnu/libcudnn.so include: /usr/include)
-- CUDNN found (library: /usr/lib/x86_64-linux-gnu/libcudnn.so include: /usr/include)
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /root/anaconda2/lib/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /root/anaconda2/lib/libmkl_gnu_thread.so
--   Library mkl_core: /root/anaconda2/lib/libmkl_core.so
--   Library iomp5: /root/anaconda2/lib/libiomp5.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL found
-- A library with BLAS API found.
-- MKLDNN headers not found; please set CMAKE_INCLUDE_PATH or MKLDNN_ROOT
-- MKLDNN library not found; please set CMAKE_LIBRARY_PATH or MKLDNN_LIBRARY
-- MKLDNN not found
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY) (found version "1.2")
-- OpenCL not found
-- Gloo not found
-- Determining NCCL version from the header file: /usr/include/nccl.h
-- NCCL_MAJOR_VERSION: 2
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
-- NCCL found
-- MPI_CXX found
-- MPI_CXX compile flags: 
-- MPI_CXX include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI_CXX LINK flags path:  -Wl,-rpath  -Wl,/usr/lib/openmpi/lib  -Wl,--enable-new-dtags
-- MPI_CXX libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
-- MPI_C found
-- MPI_C compile flags: 
-- MPI_C include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI_C LINK flags path:  -Wl,-rpath  -Wl,/usr/lib/openmpi/lib  -Wl,--enable-new-dtags
-- MPI_C libraries: /usr/lib/openmpi/lib/libmpi.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flashlight/build
```

Followed by which when I invoke `make -j 30` ,  I get the **error** as :

```
[  0%] Performing update step for 'gtest'
[  0%] Performing configure step for 'gtest'
loading initial cache file /home/flashlight/build/tests/googletest/tmp/gtest-cache-Release.cmake
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/Functions.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/BatchNorm.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/CudnnUtils.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/Utils.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/Conv2D.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/Variable.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/RNN.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/DistributedUtils.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/Pool2D.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/LayerNorm.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/distributed/DistributedApi.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/distributed/backend/cuda/DistributedBackend.cpp.o
[  0%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/AdaptiveSoftMaxLoss.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Pool2D.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Activations.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/BatchNorm.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Embedding.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Padding.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Conv2D.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/RNN.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Reorder.cpp.o
[  2%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Container.cpp.o
[  1%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Dropout.cpp.o
[  2%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Loss.cpp.o
[  2%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o
[  2%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Module.cpp.o
[  2%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/Init.cpp.o
[  2%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/View.cpp.o
[  2%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/Linear.cpp.o
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flashlight/build/tests/googletest/src/gtest
In file included from /home/flashlight/flashlight/nn/modules/Padding.cpp:8:0:
/home/flashlight/flashlight/nn/modules/Padding.h:10:36: fatal error: cereal/types/utility.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:1094: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Padding.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Padding.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/flashlight/flashlight/nn/modules/Loss.h:19:0,
                 from /home/flashlight/flashlight/nn/modules/AdaptiveSoftMaxLoss.h:10,
                 from /home/flashlight/flashlight/nn/modules/AdaptiveSoftMaxLoss.cpp:10:
/home/flashlight/flashlight/nn/modules/Container.h:22:34: fatal error: cereal/types/tuple.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:854: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/AdaptiveSoftMaxLoss.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/AdaptiveSoftMaxLoss.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/LayerNorm.h:10,
                 from /home/flashlight/flashlight/nn/modules/LayerNorm.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/nn/modules/Container.cpp:16:0:
/home/flashlight/flashlight/nn/modules/Container.h:22:34: fatal error: cereal/types/tuple.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:998: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/LayerNorm.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/LayerNorm.cpp.o] Error 1
[  3%] Performing build step for 'gtest'
CMakeFiles/flashlight.dir/build.make:902: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Container.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Container.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/backend/cuda/Pool2D.cpp:10:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:206: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/Pool2D.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/Pool2D.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/RNN.h:11,
                 from /home/flashlight/flashlight/nn/modules/RNN.cpp:10:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Transform.h:10,
                 from /home/flashlight/flashlight/nn/modules/Transform.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Activations.h:18,
                 from /home/flashlight/flashlight/nn/modules/Activations.cpp:16:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:1166: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/RNN.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/RNN.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:1190: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:830: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Activations.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Activations.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/Utils.h:10,
                 from /home/flashlight/flashlight/autograd/Utils.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/nn/modules/Loss.h:19:0,
                 from /home/flashlight/flashlight/nn/modules/Loss.cpp:18:
/home/flashlight/flashlight/nn/modules/Container.h:22:34: fatal error: cereal/types/tuple.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:1046: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Loss.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Loss.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:110: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/Utils.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/Utils.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/backend/cuda/CudnnUtils.h:13,
                 from /home/flashlight/flashlight/autograd/backend/cuda/CudnnUtils.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/distributed/DistributedApi.h:13,
                 from /home/flashlight/flashlight/distributed/DistributedApi.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:182: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/CudnnUtils.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/CudnnUtils.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:542: recipe for target 'CMakeFiles/flashlight.dir/flashlight/distributed/DistributedApi.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/distributed/DistributedApi.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Pool2D.h:11,
                 from /home/flashlight/flashlight/nn/modules/Pool2D.cpp:10:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Reorder.h:10,
                 from /home/flashlight/flashlight/nn/modules/Reorder.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/BatchNorm.h:10,
                 from /home/flashlight/flashlight/nn/modules/BatchNorm.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:1142: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Reorder.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Reorder.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:878: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/BatchNorm.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/BatchNorm.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/Init.h:27,
                 from /home/flashlight/flashlight/nn/Init.cpp:21:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
CMakeFiles/flashlight.dir/build.make:1118: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Pool2D.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Pool2D.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:782: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/Init.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/Init.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Linear.h:18,
                 from /home/flashlight/flashlight/nn/modules/Linear.cpp:18:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Conv2D.h:11,
                 from /home/flashlight/flashlight/nn/modules/Conv2D.cpp:10:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:926: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Conv2D.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Conv2D.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/backend/cuda/RNN.cpp:12:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/backend/cuda/Conv2D.cpp:13:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:230: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/RNN.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/RNN.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/Variable.cpp:16:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:1022: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Linear.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Linear.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:158: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/Conv2D.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/Conv2D.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:62: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/Variable.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/Variable.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/DistributedUtils.h:12,
                 from /home/flashlight/flashlight/nn/modules/DistributedUtils.cpp:10:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/Functions.cpp:23:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:758: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/DistributedUtils.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/DistributedUtils.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Module.cpp:18:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:1070: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Module.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Module.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:86: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/Functions.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/Functions.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Dropout.h:18,
                 from /home/flashlight/flashlight/nn/modules/Dropout.cpp:16:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/View.h:10,
                 from /home/flashlight/flashlight/nn/modules/View.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:950: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Dropout.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Dropout.cpp.o] Error 1
CMakeFiles/flashlight.dir/build.make:1214: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/View.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/View.cpp.o] Error 1
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/nn/modules/Module.h:18,
                 from /home/flashlight/flashlight/nn/modules/Embedding.h:10,
                 from /home/flashlight/flashlight/nn/modules/Embedding.cpp:8:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:974: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Embedding.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Embedding.cpp.o] Error 1
[ 50%] Built target gtest
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/autograd/backend/cuda/BatchNorm.cpp:14:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:134: recipe for target 'CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/BatchNorm.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/autograd/backend/cuda/BatchNorm.cpp.o] Error 1
[100%] Built target gtest_main
[  3%] No install step for 'gtest'
In file included from /home/flashlight/flashlight/autograd/Variable.h:24:0,
                 from /home/flashlight/flashlight/distributed/DistributedApi.h:13,
                 from /home/flashlight/flashlight/distributed/backend/cuda/DistributedBackend.cpp:17:
/home/flashlight/flashlight/common/Serialization.h:18:29: fatal error: cereal/access.hpp: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:590: recipe for target 'CMakeFiles/flashlight.dir/flashlight/distributed/backend/cuda/DistributedBackend.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/distributed/backend/cuda/DistributedBackend.cpp.o] Error 1
CMakeFiles/Makefile2:931: recipe for target 'CMakeFiles/flashlight.dir/all' failed
make[1]: *** [CMakeFiles/flashlight.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Completed 'gtest'
[  3%] Built target gtest
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```

Possibly its due to the `Cereal` library, I cloned the Github repo of `Cereal`, and as its mentioned it doesn't require any **installation** , I tried adding the path to environment variables as well as tried copying the `cereal` dir to `/home/flashlight/flashlight/common/` directory, however still then the build process is unable to pickup `cereal` .

Am I missing something important here? Please let me know. Thanks

**Comment by jacobkahn** [comment]
@shaheenkdr — have you installed [cereal](https://github.com/USCiLab/cereal) headers? See https://github.com/facebookresearch/flashlight/issues/9 and the [build requirements](https://fl.readthedocs.io/en/latest/installation.html#build-requirements).

**Comment by shaheenkdr** [comment]
@jacobkahn Thanks for the quick response, been struggling here for quite few days as I come from a non c/cpp environment.  I read the issue #9 prior to opening this issue.

Quoting from Cereal's install directory,

" *cereal can be directly included in your project or installed anywhere you can access header files. Grab the latest version from Github or use the download links above, then drop the cereal folder from the include directory (cereal_base_dir/include/cereal) somewhere your project can find. There’s nothing to build or make - cereal is header only.* "

When you say `have you installed cereal headers?` , Did you intend to say have I copied the headers to where the project can find ?  If that's what you meant, I tried downloading the library, the `develop` branch and tried moving it to `/home/flashlight/flashlight/common/` , Let me know if I have to do anything contrary to that?

**Comment by jacobkahn** [comment]
@shaheenkdr — before I continue, I'll be sending a change shortly which automatically downloads and installs cereal headers for you, so if you're still having trouble, that change should be in pretty soon.

The process for building and installing cereal headers is as follows:
1. Clone [cereal](https://github.com/USCiLab/cereal), and switch to the `develop` branch:
```
git clone https://github.com/USCiLab/cereal.git && cd cereal
git checkout develop
```
2. Build and install the headers:
```
mkdir -p build && cd build
cmake .. -DJUST_INSTALL_CEREAL=ON
make -j4
```
3. Actually move the headers to the install directory:
```
sudo make install -j4
```

When you build flashlight, it should properly find those headers.

**Comment by shaheenkdr** [comment]
@jacobkahn Thanks a ton, that resolved the issue 👍 , however,  build now produces another set of issues, I probably should close this issue and open another
