### ISSUE TITLE
Setting MPI_C and MPI_CXX

### ISSUE THREAD

**Issue by vyraun** [facebookresearch/flashlight#53]
Hi,

I am getting an error when building flashlight:

cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CUDA
-- ArrayFire found (include: /home/vraunak/cnns/arrayfire/include, library: ArrayFire::afcuda)
-- CUDA found (library: /usr/lib/x86_64-linux-gnu/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/include)
-- Found CUDNN: (lib: /usr/lib/x86_64-linux-gnu/libcudnn.so include: /usr/include)
-- CUDNN found (library: /usr/lib/x86_64-linux-gnu/libcudnn.so include: /usr/include)
-- Gloo found
-- Determining NCCL version from the header file: /usr/include/nccl.h
-- NCCL_MAJOR_VERSION: 2
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
-- NCCL found
-- MPI not found
CMake Error at flashlight/distributed/CMakeLists.txt:67 (message):
  MPI_C and MPI_CXX not found; required to build flashlight distributed
Call Stack (most recent call first):
  CMakeLists.txt:240 (include)

-- Configuring incomplete, errors occurred!

I tried setting up MPI_C & MPI_CXX to the correct paths in the openmpi bin folder, still the error persists.

Passing the paths to cmake still gives the same error.

-DMPI_CXX_COMPILER=/home/vraunak/openmpi/bin/mpicc -DMPI_C_COMPILER=/home/vraunak/openmpi/bin/mpicxx

How to resolve the error?

**Comment by vyraun** [comment]
@tlikhomanenko @jacobkahn Hi, I had downloaded openmpi from here: https://www.open-mpi.org/software/ompi/v4.0/ and did make install into a local directory. Anything wrong with this setup? Separately, I installed lapack and boost using conda, and they weren't also recognized as well, any specific variables we need to set for those libraries as well? Thanks.

**Comment by tlikhomanenko** [comment]
hi @vyraun,

Are you using Ubuntu? 
Could you have a look at [Dockerfile](https://github.com/facebookresearch/flashlight/blob/master/Dockerfile-CUDA-Base#L29)  and try to  install OpenMPI with `apt get install openssh-server openssh-client  libopenmpi-dev libomp-dev`? Does this work for you?

**Comment by jacobkahn** [comment]
@vyraun — first — what version of CMake are you using?

OpenMPI/CMake interaction is pretty bad. In general, using these four flags works for me:
```
-DMPI_CXX_LIBRARIES=[path to wherever the object is]/libmpi_cxx.so \
-DMPI_C_LIBRARIES=[path to wherever the object is]/libmpi.so \
-DMPI_CXX_INCLUDE_PATH=[path to wherever MPI headers are] \
-DMPI_C_INCLUDE_PATH=[same header path as above]
```
- give this a try?

**Comment by jacobkahn** [comment]
Closing due to inactivity.
